layout_spectrum: 0.5990851865865585
typography_spectrum: 0.5096004390674136
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.6505802836495055
  lightness: 0.6242646511476303
  saturation: 0.1315144868094548
  rhythmicContrast: 0.8014052580889905
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c98d8ae2-d91e-44c0-8be4-495bdcccb282.png
name: megalight
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Там домики
    id: 67f3079e-00a3-46f5-9d2f-8b5cb9715968
    type: content
  - name: ghbewpgfrm
    id: 3eb539fc-f766-42bc-9471-74ffe36e09e8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/22df7538-f15c-460b-b4b6-a2c3a866ddc6.jpg
title: ПЛАН
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db0120b8-328d-4bb2-a7c9-0e833fef3569.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db0120b8-328d-4bb2-a7c9-0e833fef3569.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: классный сайт
